# Rolling nightly channel pointer.
#
# Auto-generated by .github/workflows/nightly.yml and pinned onto the `nightly`
# git ref. On `main` the hash below is a placeholder, so `atlas-desktop-nightly`
# only builds when consumed through the `nightly` ref, where CI has written the
# real AppImage hash:
#
#   nix run 'git+ssh://git@github.com/0xErwin1/atlas?ref=nightly#atlas-desktop-nightly'
#
# The repository is private: the git+ssh source uses your SSH key, but the AppImage
# asset download still needs a GitHub token (see nix/README-nightly.md).
{
  url = "https://github.com/0xErwin1/atlas/releases/download/nightly/Atlas.Desktop_0.0.0_amd64.AppImage";
  hash = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
}
