import {
  Activity,
  AlertCircle,
  AlertTriangle,
  AlignLeft,
  Anchor,
  AppWindow,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  ArrowRightLeft,
  ArrowUpRight,
  Ban,
  Baseline,
  Blocks,
  BookOpen,
  BookText,
  Bot,
  Bug,
  Building2,
  Calendar,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleDot,
  Clock,
  CloudOff,
  Code,
  Columns,
  Columns3,
  Command,
  Copy,
  CornerDownLeft,
  CornerDownRight,
  Delete,
  Diff,
  Dot,
  Download,
  Edit,
  Ellipsis,
  Expand,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FilePlus,
  Files,
  FileText,
  Filter,
  Flag,
  Focus,
  Folder,
  FolderOpen,
  FolderPlus,
  FolderRoot,
  Folders,
  FoldHorizontal,
  Form,
  Ghost,
  GitBranch,
  Github,
  Globe,
  Grid,
  Group,
  Hash,
  History,
  Home,
  Icon,
  Indent,
  Info,
  Italic,
  Kanban,
  Key,
  Keyboard,
  Layers,
  Layers3,
  LayoutDashboard,
  LayoutList,
  LayoutTemplate,
  Link,
  List,
  ListChecks,
  ListOrdered,
  Lock,
  LogOut,
  Maximize,
  Maximize2,
  Menu,
  MessageSquare,
  Minus,
  Moon,
  MoreHorizontal,
  Move,
  Option,
  PanelLeft,
  PanelRight,
  PanelRightClose,
  PanelRightOpen,
  Paperclip,
  Pencil,
  Play,
  Plus,
  Pointer,
  Presentation,
  RefreshCw,
  Replace,
  RotateCcw,
  Save,
  Scroll,
  Search,
  SearchX,
  Send,
  Settings,
  Share,
  Shield,
  ShieldAlert,
  ShieldOff,
  Sidebar,
  SlidersHorizontal,
  Sparkles,
  Square,
  SquareArrowOutUpRight,
  SquareCheck,
  SquareCheckBig,
  SquareKanban,
  Star,
  Sun,
  Table,
  Tag,
  Tags,
  Target,
  Text,
  TextCursorInput,
  Trash,
  Trash2,
  TriangleAlert,
  Type,
  Underline,
  UnfoldHorizontal,
  Unlock,
  User,
  User2,
  UserMinus,
  UserPlus,
  Users,
  Webhook,
  WrapText,
  X,
  Zap,
} from 'lucide-vue-next';
import type { Component } from 'vue';

/**
 * Every lucide glyph the app can name, keyed by the kebab-case name callers pass
 * to `Icon`. The names are resolved at runtime, so a namespace import of the
 * package would defeat tree-shaking and bundle the full set; this explicit map is
 * what keeps it to the icons actually in use. Add an entry when you use a new
 * one — `Icon.registry.test.ts` fails on a name with no entry.
 */
export const LUCIDE_ICONS: Record<string, Component> = {
  activity: Activity,
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'align-left': AlignLeft,
  anchor: Anchor,
  'app-window': AppWindow,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-right-left': ArrowRightLeft,
  'arrow-up-right': ArrowUpRight,
  ban: Ban,
  baseline: Baseline,
  blocks: Blocks,
  'book-open': BookOpen,
  'book-text': BookText,
  bot: Bot,
  bug: Bug,
  'building-2': Building2,
  calendar: Calendar,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  circle: Circle,
  'circle-dot': CircleDot,
  clock: Clock,
  'cloud-off': CloudOff,
  code: Code,
  columns: Columns,
  'columns-3': Columns3,
  command: Command,
  copy: Copy,
  'corner-down-left': CornerDownLeft,
  'corner-down-right': CornerDownRight,
  delete: Delete,
  diff: Diff,
  dot: Dot,
  download: Download,
  edit: Edit,
  ellipsis: Ellipsis,
  expand: Expand,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  file: File,
  'file-plus': FilePlus,
  'file-text': FileText,
  files: Files,
  filter: Filter,
  flag: Flag,
  focus: Focus,
  'fold-horizontal': FoldHorizontal,
  folder: Folder,
  'folder-open': FolderOpen,
  'folder-plus': FolderPlus,
  'folder-root': FolderRoot,
  folders: Folders,
  form: Form,
  ghost: Ghost,
  'git-branch': GitBranch,
  github: Github,
  globe: Globe,
  grid: Grid,
  group: Group,
  hash: Hash,
  history: History,
  home: Home,
  icon: Icon,
  indent: Indent,
  info: Info,
  italic: Italic,
  kanban: Kanban,
  key: Key,
  keyboard: Keyboard,
  layers: Layers,
  'layers-3': Layers3,
  'layout-dashboard': LayoutDashboard,
  'layout-list': LayoutList,
  'layout-template': LayoutTemplate,
  link: Link,
  list: List,
  'list-checks': ListChecks,
  'list-ordered': ListOrdered,
  lock: Lock,
  'log-out': LogOut,
  maximize: Maximize,
  'maximize-2': Maximize2,
  menu: Menu,
  'message-square': MessageSquare,
  minus: Minus,
  moon: Moon,
  'more-horizontal': MoreHorizontal,
  move: Move,
  option: Option,
  'panel-left': PanelLeft,
  'panel-right': PanelRight,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  paperclip: Paperclip,
  pencil: Pencil,
  play: Play,
  plus: Plus,
  pointer: Pointer,
  presentation: Presentation,
  'refresh-cw': RefreshCw,
  replace: Replace,
  'rotate-ccw': RotateCcw,
  save: Save,
  scroll: Scroll,
  search: Search,
  'search-x': SearchX,
  send: Send,
  settings: Settings,
  share: Share,
  shield: Shield,
  'shield-alert': ShieldAlert,
  'shield-off': ShieldOff,
  sidebar: Sidebar,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  square: Square,
  'square-arrow-out-up-right': SquareArrowOutUpRight,
  'square-check': SquareCheck,
  'square-check-big': SquareCheckBig,
  'square-kanban': SquareKanban,
  star: Star,
  sun: Sun,
  table: Table,
  tag: Tag,
  tags: Tags,
  target: Target,
  text: Text,
  'text-cursor-input': TextCursorInput,
  trash: Trash,
  'trash-2': Trash2,
  'triangle-alert': TriangleAlert,
  type: Type,
  underline: Underline,
  'unfold-horizontal': UnfoldHorizontal,
  unlock: Unlock,
  user: User,
  'user-2': User2,
  'user-minus': UserMinus,
  'user-plus': UserPlus,
  users: Users,
  webhook: Webhook,
  'wrap-text': WrapText,
  x: X,
  zap: Zap,
};
