use axum::{Json, response::IntoResponse};
use utoipa::OpenApi;
use utoipa_scalar::{Scalar, Servable as _};

use atlas_api::{
    dtos::{
        ApiKeyCreated, ApiKeyDto, ChangePasswordRequest, CreateApiKeyRequest, CreateGrantRequest,
        CreateProjectRequest, CreateUserRequest, CreateWorkspaceRequest, GrantDto, GrantPrincipal,
        LoginRequest, LoginResponse, MeResponse, PrincipalDto, ProjectDto, ResetPasswordRequest,
        ServerMetaDto, SetSystemAdminRequest, UiStateDto, UpdateMeRequest, UpdateProjectRequest,
        UpdateUiStateRequest, UpdateWorkspaceRequest, UserDto, WorkspaceDto,
        boards_tasks::{
            ActivityEntryDto, AddAssigneeRequest, AssigneeDto, BoardDto, BoardSummaryDto,
            ChecklistItemDto, ColumnDto, CreateBoardRequest, CreateChecklistItemRequest,
            CreateColumnRequest, CreateReferenceRequest, CreateSubtaskRequest, CreateTaskRequest,
            MoveTaskRequest, PromoteChecklistItemRequest, PromotionDto, ReferenceDto,
            TaskBacklinkDto, TaskDto, TaskPropertiesDto, TaskSummaryDto, UpdateBoardRequest,
            UpdateChecklistItemRequest, UpdateColumnRequest, UpdateTaskRequest,
        },
        documents::{
            ActorDto, AttachmentDto, BacklinkDto, ConflictProblemDto, CopyDocumentRequest,
            CreateDocumentRequest, DocumentDto, DocumentSummaryDto, FrontmatterDto,
            MoveDocumentRequest, RevisionContentDto, RevisionMetaDto, UpdateContentRequest,
            UpdateDocumentRequest,
        },
        folders::{
            CopyFolderRequest, CreateFolderRequest, FolderDto, MoveFolderRequest,
            RenameFolderRequest,
        },
        saved_searches::{CreateSavedSearchRequest, RenameSavedSearchRequest, SavedSearchDto},
        search::{SearchHitDto, SearchKindDto},
        status_templates::{
            CreateStatusTemplateRequest, StatusTemplateDto, UpdateStatusTemplateRequest,
        },
        tags::{CreateTagRequest, TagDto, UpdateTagRequest},
        task_views::{
            CreateTaskViewRequest, TaskViewDto, TaskViewFiltersDto, UpdateTaskViewRequest,
        },
    },
    problem::ProblemDetails,
};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Atlas API",
        version = env!("CARGO_PKG_VERSION"),
        description = "Atlas knowledge and project-management platform REST API"
    ),
    paths(
        crate::routes::health::health,
        crate::routes::health::version,
        crate::routes::health::meta,
        crate::routes::auth::login,
        crate::routes::auth::logout,
        crate::routes::auth::me,
        crate::routes::auth::change_password,
        crate::routes::auth::update_me,
        crate::routes::ui_state::get_ui_state,
        crate::routes::ui_state::set_ui_state,
        crate::routes::users::list_users,
        crate::routes::users::create_user,
        crate::routes::users::disable_user,
        crate::routes::users::enable_user,
        crate::routes::users::reset_password,
        crate::routes::users::set_system_admin,
        crate::routes::workspaces::create_workspace,
        crate::routes::workspaces::list_workspaces,
        crate::routes::workspaces::get_workspace,
        crate::routes::workspaces::update_workspace,
        crate::routes::workspaces::admin_list_workspaces,
        crate::routes::api_keys::create_api_key,
        crate::routes::api_keys::list_api_keys,
        crate::routes::api_keys::revoke_api_key,
        crate::routes::projects::create_project,
        crate::routes::projects::list_projects,
        crate::routes::projects::get_project,
        crate::routes::projects::update_project,
        crate::routes::projects::delete_project,
        crate::routes::grants::create_project_grant,
        crate::routes::grants::list_project_grants,
        crate::routes::grants::delete_project_grant,
        crate::routes::grants::create_workspace_grant,
        crate::routes::grants::list_workspace_grants,
        crate::routes::grants::delete_workspace_grant,
        crate::routes::members::list_workspace_members,
        crate::routes::boards::create_board,
        crate::routes::boards::list_boards,
        crate::routes::boards::get_board,
        crate::routes::boards::update_board,
        crate::routes::boards::delete_board,
        crate::routes::boards::create_column,
        crate::routes::boards::list_columns,
        crate::routes::boards::update_column,
        crate::routes::boards::delete_column,
        crate::routes::tasks::create_task,
        crate::routes::tasks::list_tasks,
        crate::routes::tasks::list_workspace_tasks,
        crate::routes::tasks::get_task,
        crate::routes::tasks::update_task,
        crate::routes::tasks::delete_task,
        crate::routes::tasks::move_task,
        crate::routes::tasks::list_assignees,
        crate::routes::tasks::add_assignee,
        crate::routes::tasks::remove_assignee,
        crate::routes::tasks::list_references,
        crate::routes::tasks::create_reference,
        crate::routes::tasks::delete_reference,
        crate::routes::tasks::list_backlinks,
        crate::routes::tasks::list_checklist,
        crate::routes::tasks::create_checklist_item,
        crate::routes::tasks::update_checklist_item,
        crate::routes::tasks::delete_checklist_item,
        crate::routes::tasks::promote_checklist_item,
        crate::routes::tasks::list_subtasks,
        crate::routes::tasks::create_subtask,
        crate::routes::tasks::promote_subtask,
        crate::routes::tasks::list_activity,
        crate::routes::documents::create_document,
        crate::routes::documents::list_documents,
        crate::routes::documents::get_document,
        crate::routes::documents::update_document,
        crate::routes::documents::delete_document,
        crate::routes::documents::update_content,
        crate::routes::documents::list_history,
        crate::routes::documents::list_backlinks,
        crate::routes::documents::get_frontmatter,
        crate::routes::documents::upload_attachment,
        crate::routes::documents::list_attachments,
        crate::routes::documents::get_revision_content,
        crate::routes::documents::download_attachment,
        crate::routes::documents::delete_attachment,
        crate::routes::documents::move_document,
        crate::routes::documents::copy_document,
        crate::routes::folders::create_folder,
        crate::routes::folders::list_folders,
        crate::routes::folders::get_folder,
        crate::routes::folders::rename_folder,
        crate::routes::folders::move_folder,
        crate::routes::folders::copy_folder,
        crate::routes::folders::delete_folder,
        crate::routes::search::search,
        crate::routes::tags::list_tags,
        crate::routes::tags::create_tag,
        crate::routes::tags::list_used_labels,
        crate::routes::tags::patch_tag,
        crate::routes::tags::delete_tag,
        crate::routes::status_templates::list_status_templates,
        crate::routes::status_templates::create_status_template,
        crate::routes::status_templates::update_status_template,
        crate::routes::status_templates::delete_status_template,
        crate::routes::status_templates::apply_status_templates,
        crate::routes::saved_searches::list_saved_searches,
        crate::routes::saved_searches::create_saved_search,
        crate::routes::saved_searches::rename_saved_search,
        crate::routes::saved_searches::delete_saved_search,
        crate::routes::task_views::list_task_views,
        crate::routes::task_views::create_task_view,
        crate::routes::task_views::get_task_view,
        crate::routes::task_views::update_task_view,
        crate::routes::task_views::delete_task_view,
    ),
    components(schemas(
        LoginRequest,
        LoginResponse,
        MeResponse,
        ServerMetaDto,
        UiStateDto,
        UpdateUiStateRequest,
        ChangePasswordRequest,
        UpdateMeRequest,
        ResetPasswordRequest,
        SetSystemAdminRequest,
        CreateUserRequest,
        UserDto,
        CreateApiKeyRequest,
        ApiKeyCreated,
        ApiKeyDto,
        CreateProjectRequest,
        UpdateProjectRequest,
        ProjectDto,
        CreateGrantRequest,
        GrantPrincipal,
        GrantDto,
        PrincipalDto,
        CreateWorkspaceRequest,
        UpdateWorkspaceRequest,
        WorkspaceDto,
        ProblemDetails,
        CreateDocumentRequest,
        UpdateDocumentRequest,
        UpdateContentRequest,
        MoveDocumentRequest,
        CopyDocumentRequest,
        DocumentDto,
        DocumentSummaryDto,
        RevisionMetaDto,
        RevisionContentDto,
        BacklinkDto,
        FrontmatterDto,
        AttachmentDto,
        ActorDto,
        ConflictProblemDto,
        BoardDto,
        BoardSummaryDto,
        ColumnDto,
        CreateBoardRequest,
        UpdateBoardRequest,
        CreateColumnRequest,
        UpdateColumnRequest,
        TaskDto,
        TaskSummaryDto,
        TaskPropertiesDto,
        CreateTaskRequest,
        UpdateTaskRequest,
        MoveTaskRequest,
        AssigneeDto,
        AddAssigneeRequest,
        ReferenceDto,
        TaskBacklinkDto,
        CreateReferenceRequest,
        ChecklistItemDto,
        CreateChecklistItemRequest,
        CreateSubtaskRequest,
        UpdateChecklistItemRequest,
        PromotionDto,
        PromoteChecklistItemRequest,
        ActivityEntryDto,
        SearchHitDto,
        SearchKindDto,
        CreateFolderRequest,
        RenameFolderRequest,
        MoveFolderRequest,
        CopyFolderRequest,
        FolderDto,
        TagDto,
        CreateTagRequest,
        UpdateTagRequest,
        StatusTemplateDto,
        CreateStatusTemplateRequest,
        UpdateStatusTemplateRequest,
        SavedSearchDto,
        CreateSavedSearchRequest,
        RenameSavedSearchRequest,
        TaskViewDto,
        TaskViewFiltersDto,
        CreateTaskViewRequest,
        UpdateTaskViewRequest,
    )),
    tags(
        (name = "auth", description = "Authentication and session management"),
        (name = "users", description = "User management (root-only)"),
        (name = "meta", description = "Server metadata"),
        (name = "ui-state", description = "Per-user UI state"),
        (name = "api-keys", description = "Workspace API key management"),
        (name = "projects", description = "Project CRUD"),
        (name = "grants", description = "Permission grant management"),
        (name = "workspaces", description = "Workspace metadata"),
        (name = "documents", description = "Document management"),
        (name = "boards", description = "Board and column management"),
        (name = "tasks", description = "Task management"),
        (name = "folders", description = "Folder management"),
        (name = "search", description = "Unified full-text search"),
        (name = "tags", description = "Workspace tag registry"),
        (name = "status-templates", description = "Workspace default status templates"),
        (name = "saved-searches", description = "Per-owner saved search registry"),
        (name = "task-views", description = "Per-owner task filter views"),
    )
)]
pub(crate) struct ApiDoc;

pub(crate) async fn openapi_json() -> impl IntoResponse {
    Json(ApiDoc::openapi())
}

pub(crate) fn scalar_router<S>() -> axum::Router<S>
where
    S: Clone + Send + Sync + 'static,
{
    axum::Router::from(Scalar::with_url("/scalar", ApiDoc::openapi()))
}

/// Expose the assembled `OpenApi` document for test assertions.
pub fn openapi() -> utoipa::openapi::OpenApi {
    ApiDoc::openapi()
}
