/// Classification of a route's access control requirement.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum RouteKind {
    /// No authentication required.
    Public,
    /// Any authenticated principal (user or api key).
    AuthnRequired,
    /// Any authenticated member of the workspace in the `{ws}` path segment.
    WorkspaceMember,
}

/// A single route entry — the shared registry that links the protection audit and
/// the OpenAPI drift test.
///
/// This registry is the single source of truth developers must keep in sync with
/// `lib.rs`. Two directions are enforced by tests:
/// - Registry → router: `all_registry_entries_are_wired_in_router` calls every
///   entry and asserts the response is not 404.
/// - Registry → OpenAPI doc: `openapi_document_paths_match_router` asserts every
///   declared `openapi_path` is present in the generated document.
///
/// The reverse directions are NOT automatically enforced: a route added to `lib.rs`
/// without a registry entry is not caught, and an OpenAPI annotation without a
/// registry entry is not caught. axum 0.8 exposes no Router introspection, so a
/// fully router-derived check is not feasible within axum's type system.
pub struct RouteEntry {
    pub method: &'static str,
    /// Path template using `{param}` placeholders. Workspace-scoped paths use `{ws}`.
    /// For the 401 sweep a concrete path is needed; use a sentinel value for params
    /// other than `{ws}` (e.g. `00000000-0000-0000-0000-000000000001` for uuid params,
    /// `nonexistent-slug` for slug params).
    pub path_template: &'static str,
    pub kind: RouteKind,
    /// Whether this route must appear in the OpenAPI document.
    pub openapi_path: Option<&'static str>,
    /// The API-key capability (`"family:action"`) an agent must hold to call this
    /// route, or `None` when the route has no capability gate (human-only surface,
    /// AdminMin-only surface, or a cross-family feed left ungated in v1 — see
    /// `ApiKeyScope`/`Capability` for the closed catalog). Enforced black-box by
    /// `api_capability_sweep.rs`.
    pub capability: Option<&'static str>,
}

pub static ROUTE_REGISTRY: &[RouteEntry] = &[
    // ---- Public routes ----
    RouteEntry {
        method: "GET",
        path_template: "/health",
        kind: RouteKind::Public,
        openapi_path: Some("/health"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/version",
        kind: RouteKind::Public,
        openapi_path: Some("/version"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/auth/login",
        kind: RouteKind::Public,
        openapi_path: Some("/v1/auth/login"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/activate/nonexistent-token-sentinel",
        kind: RouteKind::Public,
        openapi_path: Some("/v1/activate/{token}"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/activate/nonexistent-token-sentinel",
        kind: RouteKind::Public,
        openapi_path: Some("/v1/activate/{token}"),
        capability: None,
    },
    // ---- Auth (any authenticated principal) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/auth/logout",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/auth/logout"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/auth/me",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/auth/me"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/auth/change-password",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/auth/change-password"),
        capability: None,
    },
    // ---- Self-service profile and server metadata (any authenticated principal) ----
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/users/me",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/me"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/meta",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/meta"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/me/ui-state",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/me/ui-state"),
        capability: None,
    },
    RouteEntry {
        method: "PUT",
        path_template: "/v1/me/ui-state",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/me/ui-state"),
        capability: None,
    },
    // ---- User management (root-only, but still require authn) ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/users",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/disable",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/disable"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/enable",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/enable"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/reset-password",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/reset-password"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/activation-link",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/activation-link"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/system-admin",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/system-admin"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/users/00000000-0000-0000-0000-000000000001/memberships",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/users/{user_id}/memberships"),
        capability: None,
    },
    // ---- Workspace-scoped routes ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/workspaces"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/workspaces"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}"),
        capability: None,
    },
    // ---- Admin (root-only) routes ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/admin/workspaces",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/admin/workspaces"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/admin/workspaces/{ws}",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/admin/workspaces/{ws}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/admin/workspaces/{ws}",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/admin/workspaces/{ws}"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/admin/audit",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/admin/audit"),
        capability: None,
    },
    // ---- Top-level API key routes (user-owned, workspace-independent; human-only) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/api-keys",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/api-keys",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/api-keys/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys/{key_id}"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/api-keys/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys/{key_id}"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/api-keys/00000000-0000-0000-0000-000000000001/grants",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys/{key_id}/grants"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/api-keys/00000000-0000-0000-0000-000000000001/grants/00000000-0000-0000-0000-000000000002",
        kind: RouteKind::AuthnRequired,
        openapi_path: Some("/v1/api-keys/{key_id}/grants/{grant_id}"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/projects",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects"),
        capability: Some("projects:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects"),
        capability: Some("projects:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}"),
        capability: Some("projects:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}"),
        capability: Some("projects:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}"),
        capability: Some("projects:delete"),
    },
    // ---- Grants (human-only management surface) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/grants",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/grants"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/grants",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/grants"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/grants/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/grants/{grant_id}"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/grants",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/grants"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/grants",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/grants"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/grants/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/grants/{grant_id}"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/members",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/members"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/members",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/members"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/assignable-users",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/assignable-users"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/members/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/members/{user_id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/members/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/members/{user_id}"),
        capability: None,
    },
    // ---- Document routes ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/documents",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/documents"),
        capability: Some("docs:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/documents",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/documents"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}"),
        capability: Some("docs:delete"),
    },
    RouteEntry {
        method: "PUT",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/content",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/content"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/history",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/history"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/revisions/1",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/revisions/{seq}"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/backlinks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/backlinks"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/frontmatter",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/frontmatter"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/attachments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/attachments"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/attachments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/attachments"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/attachments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/attachments/{attachment_id}"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/attachments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/attachments/{attachment_id}"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/move",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/move"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/copy",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/copy"),
        capability: Some("docs:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/comments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/comments"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/comments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/comments"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/comments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/comments/{comment_id}"),
        capability: Some("docs:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/comments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/comments/{comment_id}"),
        capability: Some("docs:update"),
    },
    // ---- Board routes ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/boards",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/boards"),
        capability: Some("boards:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/boards",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/boards"),
        capability: Some("boards:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}"),
        capability: Some("boards:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}"),
        capability: Some("boards:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}"),
        capability: Some("boards:delete"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/columns",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/columns"),
        capability: Some("boards:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/columns",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/columns"),
        capability: Some("boards:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/columns/00000000-0000-0000-0000-000000000002",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/columns/{column_id}"),
        capability: Some("boards:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/columns/00000000-0000-0000-0000-000000000002",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/columns/{column_id}"),
        capability: Some("boards:update"),
    },
    // ---- Task routes ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/tasks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/tasks"),
        capability: Some("tasks:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/tasks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/tasks"),
        capability: Some("tasks:read"),
    },
    // ---- Board presence (ephemeral view signal) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/presence",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/presence"),
        capability: Some("boards:read"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/presence",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/presence"),
        capability: Some("boards:read"),
    },
    // ---- Document presence (ephemeral view signal) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/presence",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/presence"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/documents/nonexistent-slug/presence",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/documents/{slug}/presence"),
        capability: Some("docs:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}"),
        capability: Some("tasks:delete"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/move",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/move"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/assignees",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/assignees"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/assignees",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/assignees"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/assignees/user:00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/assignees/{assignee_ref}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/references",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/references"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/references",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/references"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/references/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/references/{reference_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/attachments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/attachments"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/attachments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/attachments"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/attachments/00000000-0000-0000-0000-000000000001/content",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some(
            "/v1/workspaces/{ws}/tasks/{readable_id}/attachments/{attachment_id}/content",
        ),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/attachments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/attachments/{attachment_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/backlinks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/backlinks"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/checklist",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/checklist"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/checklist",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/checklist"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/checklist/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/checklist/{item_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/checklist/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/checklist/{item_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/checklist/00000000-0000-0000-0000-000000000001/promote",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/checklist/{item_id}/promote"),
        capability: Some("tasks:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/comments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/comments"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/comments",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/comments"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/comments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/comments/{comment_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/comments/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/comments/{comment_id}"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/subtasks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/subtasks"),
        capability: Some("tasks:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/subtasks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/subtasks"),
        capability: Some("tasks:create"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/promote",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/promote"),
        capability: Some("tasks:update"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tasks/ATL-0/activity",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tasks/{readable_id}/activity"),
        capability: Some("tasks:read"),
    },
    // ---- Workspace-wide activity / audit ----
    // `/activity` carries capability: None here but is gated `tasks:read` in-handler
    // (manual gate, like list_workspace_tasks); the feed is task-family only. `/audit`
    // is owner/admin-only and unreachable by an API key.
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/activity",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/activity"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/audit",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/audit"),
        capability: None,
    },
    // ---- Folder routes ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/folders",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/folders"),
        capability: Some("folders:create"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/projects/nonexistent-proj/folders",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/projects/{project_slug}/folders"),
        capability: Some("folders:read"),
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/folders/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/folders/{folder_id}"),
        capability: Some("folders:read"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/folders/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/folders/{folder_id}"),
        capability: Some("folders:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/folders/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/folders/{folder_id}"),
        capability: Some("folders:delete"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/folders/00000000-0000-0000-0000-000000000001/move",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/folders/{folder_id}/move"),
        capability: Some("folders:update"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/folders/00000000-0000-0000-0000-000000000001/copy",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/folders/{folder_id}/copy"),
        capability: Some("folders:create"),
    },
    // ---- Live updates (Server-Sent Events) ----
    //
    // SSE is not modelled in OpenAPI (utoipa cannot express an event stream), so
    // `openapi_path` is None: the endpoint is exercised by the 401-sweep and the
    // registry→router audit, but excluded from the OpenAPI drift test. The web app
    // consumes it via `EventSource`, not the generated client. It is also a
    // cross-family feed left ungated by capability in v1.
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/events",
        kind: RouteKind::WorkspaceMember,
        openapi_path: None,
        capability: None,
    },
    // ---- Search (cross-family feed, ungated in v1) ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/search",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/search"),
        capability: None,
    },
    // ---- Tags ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tags",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tags"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/tags",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tags"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/tags/used",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tags/used"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/tags/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tags/{tag_id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/tags/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/tags/{tag_id}"),
        capability: None,
    },
    // ---- Status templates (folded into the boards family; apply-to-board is boards:update) ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/status-templates",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/status-templates"),
        capability: Some("boards:read"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/status-templates",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/status-templates"),
        capability: Some("boards:create"),
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/status-templates/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/status-templates/{template_id}"),
        capability: Some("boards:update"),
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/status-templates/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/status-templates/{template_id}"),
        capability: Some("boards:delete"),
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/boards/00000000-0000-0000-0000-000000000001/apply-status-templates",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/boards/{board_id}/apply-status-templates"),
        capability: Some("boards:update"),
    },
    // ---- Property definitions ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/property-definitions",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/property-definitions"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/property-definitions",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/property-definitions"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/property-definitions/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/property-definitions/{property_definition_id}"),
        capability: None,
    },
    // ---- Saved searches ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/saved-searches",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/saved-searches"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/saved-searches",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/saved-searches"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/saved-searches/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/saved-searches/{id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/saved-searches/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/saved-searches/{id}"),
        capability: None,
    },
    // ---- Groups (not one of the five capability families) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/groups",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/groups",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/groups/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups/{group_id}"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/groups/00000000-0000-0000-0000-000000000001/members",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups/{group_id}/members"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/groups/00000000-0000-0000-0000-000000000001/members",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups/{group_id}/members"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/groups/00000000-0000-0000-0000-000000000001/members/00000000-0000-0000-0000-000000000002",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/groups/{group_id}/members/{user_id}"),
        capability: None,
    },
    // ---- Task views ----
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/task-views",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/task-views"),
        capability: None,
    },
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/task-views",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/task-views"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/task-views/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/task-views/{id}"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/task-views/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/task-views/{id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/task-views/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/task-views/{id}"),
        capability: None,
    },
    // ---- Integration configs (admin-only, agent-unreachable) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/integration-configs",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/integration-configs"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/integration-configs",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/integration-configs"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/integration-configs/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/integration-configs/{config_id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/integration-configs/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/integration-configs/{config_id}"),
        capability: None,
    },
    // ---- Automation rules (admin-only, agent-unreachable) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/automation-rules",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/automation-rules"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/automation-rules",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/automation-rules"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/automation-rules/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/automation-rules/{rule_id}"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/automation-rules/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/automation-rules/{rule_id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/automation-rules/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/automation-rules/{rule_id}"),
        capability: None,
    },
    // ---- External event ingestion (public) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/integrations/github/events",
        kind: RouteKind::Public,
        openapi_path: Some("/v1/workspaces/{ws}/integrations/{integration}/events"),
        capability: None,
    },
    // ---- Webhooks (admin-only, agent-unreachable) ----
    RouteEntry {
        method: "POST",
        path_template: "/v1/workspaces/{ws}/webhooks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/webhooks",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/webhooks/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks/{webhook_id}"),
        capability: None,
    },
    RouteEntry {
        method: "PATCH",
        path_template: "/v1/workspaces/{ws}/webhooks/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks/{webhook_id}"),
        capability: None,
    },
    RouteEntry {
        method: "DELETE",
        path_template: "/v1/workspaces/{ws}/webhooks/00000000-0000-0000-0000-000000000001",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks/{webhook_id}"),
        capability: None,
    },
    RouteEntry {
        method: "GET",
        path_template: "/v1/workspaces/{ws}/webhooks/00000000-0000-0000-0000-000000000001/deliveries",
        kind: RouteKind::WorkspaceMember,
        openapi_path: Some("/v1/workspaces/{ws}/webhooks/{webhook_id}/deliveries"),
        capability: None,
    },
];
