//! Router audit mechanism (design D1/D2/D4/D5, `v2-e3-s2-router-audit`).
//!
//! `component_routes!` builds a component's axum `Router` and its
//! `declared_routes()` audit table from one token list, so a route cannot
//! exist in the router without a matching table entry: the router-building
//! `.route()` calls and the audit-readable entries are two outputs of the
//! same macro expansion, not two hand-kept structures. This module ships the
//! shared data types and the two audit comparisons every per-component audit
//! test reuses verbatim (this PR's scratch fixtures now; PR2–PR4's real
//! `platform`/`custos`/`acta` components later) — one implementation of each
//! comparison, not one per component.
//!
//! See `authz::extract_scope` for how the per-route `Capability` is read off
//! each handler's real `Authorized<R, M, S>` signature.
#![allow(
    dead_code,
    reason = "PR2-PR4 wire declared_routes()/diff_route_sets()/diff_declared_and_enforced() \
              into real per-component audits; this PR proves the mechanism against scratch \
              fixtures only, so nothing outside tests calls them yet"
)]

use std::collections::{HashMap, HashSet};
use std::hash::Hash;

use atlas_core::ids::ActionId;
use atlas_core::registry::HttpMethod;
use atlas_custos::capability::Capability;

/// What `component_routes!` learned about a route's authorization gate.
///
/// `Extracted` is the normal case: the handler took `Authorized<R, M, S>`,
/// and the compiler resolved `S::CAPABILITY` for us (`None` for `NoScope`,
/// `Some(_)` for a pinned capability marker). `Unauthenticated` is the
/// capability-extraction exemption (D5): the handler has no `Authorized<...>`
/// extractor at all (login, activate, health/ready/version), so there is
/// nothing to extract — the declare-and-verify audit only checks that the
/// registry side declares `action: None` for it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) enum DeclaredScope {
    Extracted(Option<Capability>),
    Unauthenticated,
}

/// One route entry generated by `component_routes!`, read by the audits.
///
/// `path` is the raw literal from the macro invocation, not a validated
/// `atlas_core::registry::RoutePath` — validating route-path syntax is the
/// registry's job (`RouteDeclaration.path`); this table only ever needs to
/// compare `(method, path)` strings against the registry's declared paths.
#[derive(Debug, Clone, Copy)]
pub(crate) struct AuditedRoute {
    pub method: HttpMethod,
    pub path: &'static str,
    pub scope: DeclaredScope,
    /// Whether `component_routes!`'s `idempotent` modifier applied the
    /// `Idempotency-Key` middleware layer to this route (`v2-e3-s3` D6). Set
    /// from the same macro expansion/token that wires the layer, so a route
    /// cannot be layered without this being `true` and cannot claim `true`
    /// without being layered — the same "one macro expansion, one fact"
    /// property `scope` already has for capability extraction. Hand-declared
    /// routes outside the macro (`routes::custos::public`,
    /// `routes::acta::{public,layered}`) set this by hand at their own
    /// `AuditedRoute` literal, mirroring how they hand-declare `scope`.
    pub idempotent: bool,
    /// Whether `component_routes!`'s `one_shot` modifier (valid only
    /// alongside `idempotent`, `v2-e3-s3` PR4 scoped correction) wired this
    /// route's layer to `idempotency_middleware_store_briefly` rather than
    /// the default `idempotency_middleware_release` (D6). Set from the same
    /// macro token that picks the layer, so a route cannot claim `true` here
    /// without actually being layered with the `StoreBriefly` policy — the
    /// same "one macro expansion, one fact" property `idempotent` already
    /// has. Hand-declared routes outside the macro set this by hand, like
    /// `idempotent`; today none of them are `true`
    /// ([`ONE_SHOT_IDEMPOTENT_ROUTES`] names only two macro-wired routes).
    pub one_shot: bool,
}

/// The result of comparing two `(method, path)` sets in both directions
/// (INV-SET): never a `.len()` comparison, always the named offending
/// routes. `left_only`/`right_only` name which side is missing the route,
/// not which side is "correct" — callers pick that framing from which set
/// they passed as `left` vs `right`.
///
/// Generic over the path representation (`P`) because PR1's scratch fixtures
/// compare `&'static str` literals on both sides, while PR2+'s real
/// per-component audits compare `declared_routes()`'s `&'static str` macro
/// literals against `ComponentEntry.api.routes`'s owned `RoutePath` strings
/// — the same set-equality comparison, just over a different (still
/// `Eq + Hash`) path type on each side, unified by the caller before calling
/// this function.
/// `pub`, unlike this module's other data types (see
/// [`platform_route_paths`]'s doc for why): `tests/idempotency_declare_and_verify_audit.rs`
/// (`v2-e3-s3` PR4) is an integration test, compiled as a separate crate,
/// and reuses this exact comparison rather than reimplementing it.
#[derive(Debug, PartialEq, Eq)]
pub struct RouteSetDiff<P> {
    pub left_only: Vec<(HttpMethod, P)>,
    pub right_only: Vec<(HttpMethod, P)>,
}

impl<P> Default for RouteSetDiff<P> {
    fn default() -> Self {
        Self {
            left_only: Vec::new(),
            right_only: Vec::new(),
        }
    }
}

impl<P> RouteSetDiff<P> {
    pub fn is_empty(&self) -> bool {
        self.left_only.is_empty() && self.right_only.is_empty()
    }
}

/// The one bidirectional set-equality comparison every per-component audit
/// reuses (D2): a route present on only one side is named, in both
/// directions, by a single implementation. This is what T1.6 proves stays
/// true across every scenario (matched, router-only, declared-only, or
/// both at once) — PR2–PR4 call this same function with `declared_routes()`
/// on one side and `ComponentEntry.api.routes` on the other.
pub fn diff_route_sets<P>(
    left: &HashSet<(HttpMethod, P)>,
    right: &HashSet<(HttpMethod, P)>,
) -> RouteSetDiff<P>
where
    P: Eq + Hash + Clone,
{
    RouteSetDiff {
        left_only: left.difference(right).cloned().collect(),
        right_only: right.difference(left).cloned().collect(),
    }
}

/// The namespace whose form the idempotency store keys on, so one logical
/// operation has one dedup record no matter which mount the client used.
/// Equal to [`V1_NAMESPACE`], the form rows stored before the dual mount
/// already carry.
pub const CANONICAL_NAMESPACE: &str = "/api";

/// The V1 mount prefix. Equal to [`CANONICAL_NAMESPACE`]; kept as a separate
/// name because [`namespaces_for`] reads more clearly naming both mounts by
/// their own constant than reusing the idempotency-specific name for a
/// routing concern.
pub const V1_NAMESPACE: &str = CANONICAL_NAMESPACE;

/// The V2 mount prefix, without a component segment. Never mounted on its
/// own (`v2-e3-s4` PR7, D10): every V2 route lives under
/// `V2_PREFIX/<component>`, so a request against the bare prefix matches
/// nothing.
pub const V2_PREFIX: &str = "/api/v2";

/// The two mount prefixes a route owned by `component` is reachable under
/// (`v2-e3-s4` PR7, D10): `/api` (shared by every component) and
/// `/api/v2/<component>` (this component's own V2 namespace). Replaces the
/// flat, two-entry `NAMESPACES` constant this slice's earlier PRs used: PR5
/// mounted one shared `/api/v2` for all three components, which SHELL-API-1
/// and the E3 proposal both fix with a per-component segment. Every former
/// `NAMESPACES` consumer now calls this with the route's own owning
/// component (`RouteMatrixEntry::namespaces`, `RouteMatrixEntry::component`)
/// instead of iterating one shared pair for every route.
pub fn namespaces_for(component: &str) -> [String; 2] {
    [V1_NAMESPACE.to_string(), format!("{V2_PREFIX}/{component}")]
}

/// The `/api/v2/<component>` mount `component`'s routes are served at
/// (`lib.rs::app`'s per-component nest) and, from `v2-e3-s6`, the namespace
/// the composed OpenAPI document keys them under. Reads
/// [`namespaces_for`]'s second element rather than re-deriving the prefix.
pub fn v2_namespace(component: &str) -> String {
    let [_v1, v2] = namespaces_for(component);
    v2
}

/// Joins a mount `namespace` with a namespace-relative `relative_path` (D1).
/// The single place every consumer in the proposal's blast-radius table
/// builds a concrete V1/V2 path, so no caller ever hand-concatenates a
/// literal `"/api"` a second time.
pub fn joined(namespace: &str, relative_path: &str) -> String {
    format!("{namespace}{relative_path}")
}

/// Routes mounted directly at the composition root, outside the `/api`
/// nest (`v2-e3-s4` D2/T4.X): `/health`/`/ready`/`/version` carried no
/// `/api` prefix before this slice's rewrite and must not gain one, and
/// `/openapi.json`/`/scalar` are the document's own serving endpoints,
/// also mounted outside `/api`. Every other registry-declared route lives
/// under the `/api` nest (and, from PR5, the `/api/v2` nest too).
pub const ROOT_LEVEL_PATHS: &[&str] =
    &["/health", "/ready", "/version", "/openapi.json", "/scalar"];

/// The concrete path a registry-relative `path` is actually served at under
/// `namespace` (`v2-e3-s4` D2/T4.X): a [`ROOT_LEVEL_PATHS`] member stays
/// unprefixed (it is never nested under `/api`/`/api/v2` at all); every
/// other route is [`joined`] with `namespace`. This is the one place a
/// registry-relative path is turned into the URL actually reachable on the
/// wire, so every consumer that builds a request or compares against the
/// OpenAPI document's (prefixed) path keys goes through this function
/// rather than hand-concatenating `/api` a second time.
pub fn mounted_path(namespace: &str, path: &str) -> String {
    if ROOT_LEVEL_PATHS.contains(&path) {
        path.to_string()
    } else {
        joined(namespace, path)
    }
}

/// Translates a registry-declared `ActionId` (`<component>::<family>::<action>`)
/// into the `Capability` its wire form (`family:action`) denotes, so the
/// declare-and-verify audit compares the registry's declared action against
/// the handler's enforced `S::CAPABILITY` as the SAME `Capability` type on
/// both sides, per D5's "one fact read twice." The `<component>` segment is
/// discarded: `ActionId` carries it for the registry's own uniqueness check
/// (`validate_unique_ids`'s `DuplicateAction`), but `Capability` has no
/// per-component axis — `tasks:read` means the same capability regardless of
/// which registry entry declared it.
///
/// # Panics
/// Panics if the `<family>::<action>` segment does not name a known
/// `Capability` — this is a registry-authoring bug (a typo'd action), not a
/// runtime condition callers should recover from, and every current caller
/// only invokes this on `ActionId`s already vetted by `reg5.rs`'s own
/// `reg5_registry_build.rs` workspace test.
///
/// `pub`, unlike this module's other audit internals (see
/// [`platform_route_paths`]'s doc for why): PR5's migrated
/// `api_capability_sweep.rs` is an integration test, compiled as a separate
/// crate, and needs this exact translation to read `RouteDeclaration.action`
/// off the live registry instead of the retired route registry's
/// `capability: Option<&str>` field.
#[allow(
    clippy::panic,
    reason = "an ActionId with no matching Capability is a registry-authoring bug \
              (a typo'd action), not a runtime condition callers should recover from; \
              every current caller only invokes this on ActionIds already vetted by \
              reg5.rs's own reg5_registry_build.rs workspace test"
)]
pub fn capability_from_action_id(action: &ActionId) -> Capability {
    let wire = format!("{}:{}", action.kind(), action.action());
    wire.parse().unwrap_or_else(|_| {
        panic!("registry action `{action}` has no matching Capability (wire form `{wire}`)")
    })
}

/// A route whose declared action (registry side) and enforced capability
/// (handler side, via `ExtractScope`) disagree.
#[derive(Debug, PartialEq, Eq)]
pub(crate) struct ScopeMismatch {
    pub method: HttpMethod,
    pub path: &'static str,
    pub declared: Option<Capability>,
    pub enforced: Option<Capability>,
}

/// Declare-and-verify comparison (D5): for every audited route, compares the
/// registry's declared action against the handler's actually-enforced
/// capability. `Option<Capability>` equality already covers every mismatch
/// direction the spec names (`Some`/`Some` disagreement, `Some`/`None`,
/// `None`/`Some`) with one comparison per route — unlike `diff_route_sets`,
/// this needs no separate "reverse direction" pass, because each route's
/// declared and enforced values are a single fact pair, not a set.
pub(crate) fn diff_declared_and_enforced(
    routes: &[AuditedRoute],
    declared_actions: &HashMap<(HttpMethod, &'static str), Option<Capability>>,
) -> Vec<ScopeMismatch> {
    let mut mismatches = Vec::new();

    for route in routes {
        let declared = declared_actions
            .get(&(route.method, route.path))
            .copied()
            .flatten();

        let enforced = match route.scope {
            DeclaredScope::Extracted(capability) => capability,
            DeclaredScope::Unauthenticated => None,
        };

        if declared != enforced {
            mismatches.push(ScopeMismatch {
                method: route.method,
                path: route.path,
                declared,
                enforced,
            });
        }
    }

    mismatches
}

/// Builds a component's `router(state)` and `declared_routes()` from a list
/// of paths, each carrying one or more `METHOD(handler[, exempt])` entries
/// (design D1). Both functions are generated from the same list at the same
/// macro invocation, so a route cannot exist in the router without an entry
/// in `declared_routes()` — the only way to add a route through this macro
/// is to add it to both at once.
///
/// Several methods on the same path fold into exactly one `.route()` call
/// with a chained/merged `MethodRouter` (`get(h).merge(post(h2))`), matching
/// how `lib.rs` already groups multi-method paths today (e.g.
/// `get(...).post(...)` in one call) — this is a DSL-level grouping choice,
/// not a workaround for an axum panic: axum 0.8's `Router::route` already
/// merges repeated calls to the same path internally
/// (`path_router.rs::PathRouter::route`), it only panics on a genuine
/// same-method overlap. Grouping here keeps the generated code shaped like
/// today's hand-written router and keeps `declared_routes()` emitting one
/// `AuditedRoute` per `(method, path)` pair even though the router mounts
/// the path once.
///
/// Entries default to capability extraction: `handler.declared_scope()` (via
/// `authz::ExtractScope`) reads `S::CAPABILITY` straight off the handler's
/// real `Authorized<R, M, S>` parameter. A trailing `, exempt` marks a
/// handler that has no `Authorized<...>` extractor at all (login, activate,
/// health/ready/version) — the capability-extraction exemption list (D5) —
/// and skips the extraction call, recording `DeclaredScope::Unauthenticated`
/// instead.
///
/// `state` is generic (`$state_ty`) rather than hard-coded to `AppState` so
/// this PR's scratch fixtures can exercise the mechanism without any
/// production state or database dependency; real components (PR2–PR4)
/// invoke this with `state: AppState`.
/// Trailing modifiers accepted after a handler expression: `exempt` (D5,
/// unchanged from before this slice), `idempotent` (D6, `v2-e3-s3`), and
/// `one_shot` (D6 scoped correction, `v2-e3-s3` PR4), independent of each
/// other except that `one_shot` is only valid alongside `idempotent` —
/// `post(h, one_shot)` alone has no matching macro arm and fails to compile.
/// Always write modifiers in this fixed order when more than one applies:
/// `exempt`, then `idempotent`, then `one_shot` (`post(h, idempotent)`,
/// `post(h, exempt, idempotent)`, `post(h, idempotent, one_shot)`,
/// `post(h, exempt, idempotent, one_shot)`) — the macro's modifier-list arms
/// below match that fixed order.
///
/// `idempotent` applies the `Idempotency-Key` middleware layer to THIS
/// method's `MethodRouter` only, before it merges into the path's chained
/// router — so a path with two methods (e.g. `get(..)`/`post(.., idempotent)`)
/// can layer just the one method that needs it, matching D8's per-`(method,
/// path)` granularity. The layer's 5xx policy is carried structurally by
/// WHICH middleware function the token picks (D6 scoped correction, never
/// read from the registry at request time): plain `idempotent` wires
/// `middleware::idempotency::idempotency_middleware_release`
/// (`IdempotencyPolicy { on_server_error: OnServerError::Release }` — an
/// ordinary create, whose duplicate a domain check already catches once a
/// 5xx retry re-executes); `idempotent, one_shot` wires
/// `idempotency_middleware_store_briefly`
/// (`on_server_error: OnServerError::StoreBriefly` — a one-shot side effect
/// with no domain uniqueness check, so a 5xx retry replays the stored
/// outcome briefly instead of re-executing it). The same tokens also set
/// `AuditedRoute.idempotent`/`AuditedRoute.one_shot`, so a route cannot be
/// layered without the audit seeing it and cannot claim either flag in the
/// audit without being layered accordingly (D6's "one macro expansion, one
/// fact," extended from `scope` to these two fields).
#[macro_export]
macro_rules! component_routes {
    (
        state: $state_ty:ty;
        $(
            $path:literal => [
                $( $method:ident($handler:expr $(, $modifier:ident)*) ),+ $(,)?
            ]
        );+ $(;)?
    ) => {
        pub fn router(state: $state_ty) -> ::axum::Router {
            ::axum::Router::new()
                $(
                    .route(
                        $path,
                        $crate::component_routes!(
                            @method_router state; $( $method($handler, [$($modifier),*]) ),+
                        )
                    )
                )+
                .with_state(state)
        }

        pub(crate) fn declared_routes() -> ::std::vec::Vec<$crate::router_audit::AuditedRoute> {
            ::std::vec![
                $(
                    $(
                        $crate::component_routes!(@entry $method, $path, $handler, [$($modifier),*])
                    ),+
                ),+
            ]
        }
    };

    // Folds every method on one path into a single chained/merged
    // `MethodRouter`, e.g. `get(h1).merge(post(h2)).merge(delete(h3))`,
    // applying each method's own modifier-derived layer BEFORE the merge
    // (`@layered_method`), so a per-method `idempotent` layer never leaks
    // onto a sibling method sharing the same path.
    (@method_router $state:ident; $first_m:ident($first_h:expr, [$($first_mod:ident),*]) $(, $rest_m:ident($rest_h:expr, [$($rest_mod:ident),*]))* $(,)?) => {
        $crate::component_routes!(@layered_method $state, $first_m, $first_h, [$($first_mod),*])
        $( .merge($crate::component_routes!(@layered_method $state, $rest_m, $rest_h, [$($rest_mod),*])) )*
    };

    (@layered_method $state:ident, $method:ident, $handler:expr, [idempotent]) => {
        ::axum::routing::$method($handler).layer(::axum::middleware::from_fn_with_state(
            $state.clone(),
            $crate::middleware::idempotency::idempotency_middleware_release,
        ))
    };
    (@layered_method $state:ident, $method:ident, $handler:expr, [exempt, idempotent]) => {
        ::axum::routing::$method($handler).layer(::axum::middleware::from_fn_with_state(
            $state.clone(),
            $crate::middleware::idempotency::idempotency_middleware_release,
        ))
    };
    (@layered_method $state:ident, $method:ident, $handler:expr, [idempotent, one_shot]) => {
        ::axum::routing::$method($handler).layer(::axum::middleware::from_fn_with_state(
            $state.clone(),
            $crate::middleware::idempotency::idempotency_middleware_store_briefly,
        ))
    };
    (@layered_method $state:ident, $method:ident, $handler:expr, [exempt, idempotent, one_shot]) => {
        ::axum::routing::$method($handler).layer(::axum::middleware::from_fn_with_state(
            $state.clone(),
            $crate::middleware::idempotency::idempotency_middleware_store_briefly,
        ))
    };
    (@layered_method $state:ident, $method:ident, $handler:expr, [exempt]) => {
        ::axum::routing::$method($handler)
    };
    (@layered_method $state:ident, $method:ident, $handler:expr, []) => {
        ::axum::routing::$method($handler)
    };

    (@entry $method:ident, $path:expr, $handler:expr, []) => {{
        #[allow(unused_imports, reason = "brought into scope only for the method-call below")]
        use $crate::authz::ExtractScope;
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Extracted($handler.declared_scope()),
            idempotent: false,
            one_shot: false,
        }
    }};

    (@entry $method:ident, $path:expr, $handler:expr, [idempotent]) => {{
        #[allow(unused_imports, reason = "brought into scope only for the method-call below")]
        use $crate::authz::ExtractScope;
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Extracted($handler.declared_scope()),
            idempotent: true,
            one_shot: false,
        }
    }};

    (@entry $method:ident, $path:expr, $handler:expr, [idempotent, one_shot]) => {{
        #[allow(unused_imports, reason = "brought into scope only for the method-call below")]
        use $crate::authz::ExtractScope;
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Extracted($handler.declared_scope()),
            idempotent: true,
            one_shot: true,
        }
    }};

    (@entry $method:ident, $path:expr, $handler:expr, [exempt]) => {
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Unauthenticated,
            idempotent: false,
            one_shot: false,
        }
    };

    (@entry $method:ident, $path:expr, $handler:expr, [exempt, idempotent]) => {
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Unauthenticated,
            idempotent: true,
            one_shot: false,
        }
    };

    (@entry $method:ident, $path:expr, $handler:expr, [exempt, idempotent, one_shot]) => {
        $crate::router_audit::AuditedRoute {
            method: $crate::component_routes!(@method $method),
            path: $path,
            scope: $crate::router_audit::DeclaredScope::Unauthenticated,
            idempotent: true,
            one_shot: true,
        }
    };

    (@method get) => { ::atlas_core::registry::HttpMethod::Get };
    (@method post) => { ::atlas_core::registry::HttpMethod::Post };
    (@method put) => { ::atlas_core::registry::HttpMethod::Put };
    (@method patch) => { ::atlas_core::registry::HttpMethod::Patch };
    (@method delete) => { ::atlas_core::registry::HttpMethod::Delete };
    (@method head) => { ::atlas_core::registry::HttpMethod::Head };
    (@method options) => { ::atlas_core::registry::HttpMethod::Options };
}

/// Test-only surface for T4.9's per-component mount assertion
/// (`tests/api_router_mount_assertion.rs`): each component's declared
/// `(method, path)` set for its `public` (no-auth-layer) sub-router only —
/// deliberately narrower than the component's full `declared_routes()`
/// union, which also contains routes wrapped by `require_authn`. Probing an
/// authenticated route with an unauthenticated, wrong-method request gets
/// 401 from that layer before axum's own per-path method dispatch ever runs
/// (`Router::layer` wraps each mounted path's whole `MethodRouter`,
/// including its method-not-allowed fallback — confirmed against axum
/// 0.8.9's `path_router.rs::PathRouter::layer`), so only a component's
/// genuinely public routes are safe candidates for the mount probe's
/// unauthenticated 405 proof.
///
/// Genuinely `pub`, unlike everything else in this module: integration
/// tests under `tests/` compile as a separate crate that only sees this
/// crate's public API, never `pub(crate)` items — `#[cfg(test)]` does not
/// apply to them either, since Cargo builds the library normally (not with
/// `--test`) when linking it into an integration test binary. `AuditedRoute`
/// and `DeclaredScope` stay crate-private (D5's extraction machinery is not
/// this test's concern); only the `(method, path)` pair is exposed, which is
/// all a mount probe needs. Mirrors `routes::openapi::openapi()`'s existing
/// precedent of a small `pub fn` carved out purely "for test assertions."
pub fn platform_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    component_route_paths(&crate::routes::platform::public_declared_routes())
}

/// See [`platform_route_paths`].
pub fn custos_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    component_route_paths(&crate::routes::custos::public_declared_routes())
}

/// See [`platform_route_paths`].
pub fn acta_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    component_route_paths(&crate::routes::acta::public_declared_routes())
}

/// Test-only surface for `tests/api_acta_router_parity.rs`'s data-driven
/// unauthenticated-401 proof: acta's declared `(method, path)` set for every
/// route behind `require_authn` (`acta::protected_declared_routes()`) — the
/// complement of [`acta_route_paths`], which only exposes acta's one public
/// route. Same `pub fn`-for-tests precedent as [`platform_route_paths`].
pub fn acta_protected_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    component_route_paths(&crate::routes::acta::protected_declared_routes())
}

/// Test-only surface for the `v2-e3-s3` PR4 idempotency declare-and-verify
/// audit (`tests/idempotency_declare_and_verify_audit.rs`): the `(method,
/// path)` set of routes `component_routes!`'s `idempotent` modifier (or a
/// hand-declared `AuditedRoute` literal) actually wired to the
/// `Idempotency-Key` middleware for `platform`. Compared against the
/// registry's `RouteDeclaration.idempotent: true` set (INV-SET,
/// bidirectional) — same "one macro expansion, one fact" property
/// [`platform_route_paths`] already proves for capability extraction,
/// extended to this new field.
pub fn platform_idempotent_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    idempotent_route_paths(&crate::routes::platform::declared_routes())
}

/// See [`platform_idempotent_route_paths`].
pub fn custos_idempotent_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    idempotent_route_paths(&crate::routes::custos::declared_routes())
}

/// See [`platform_idempotent_route_paths`].
pub fn acta_idempotent_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    idempotent_route_paths(&crate::routes::acta::declared_routes())
}

fn idempotent_route_paths(routes: &[AuditedRoute]) -> Vec<(HttpMethod, &'static str)> {
    routes
        .iter()
        .filter(|route| route.idempotent)
        .map(|route| (route.method, route.path))
        .collect()
}

/// Test-only surface for the `v2-e3-s3` PR4 scoped correction's declare-and-
/// verify audit (`tests/idempotency_declare_and_verify_audit.rs`): the
/// `(method, path)` set of routes `component_routes!`'s `one_shot` modifier
/// actually wired to `idempotency_middleware_store_briefly` for `acta` — the
/// only component with any `one_shot` route today. Compared against
/// [`ONE_SHOT_IDEMPOTENT_ROUTES`] (INV-SET, bidirectional), same "one macro
/// expansion, one fact" property [`platform_idempotent_route_paths`] already
/// proves for `idempotent` itself, extended to this new field.
pub fn acta_one_shot_route_paths() -> Vec<(atlas_core::registry::HttpMethod, &'static str)> {
    one_shot_route_paths(&crate::routes::acta::declared_routes())
}

fn one_shot_route_paths(routes: &[AuditedRoute]) -> Vec<(HttpMethod, &'static str)> {
    routes
        .iter()
        .filter(|route| route.one_shot)
        .map(|route| (route.method, route.path))
        .collect()
}

/// The `idempotent: true` routes whose 5xx policy is
/// `middleware::idempotency::OnServerError::StoreBriefly` rather than the
/// default `Release` (ORCHESTRATOR DECISION, 2026-09-02, scoped correction
/// to `R4-5xx-release-duplicates-one-shot-jobs`, D6): each enqueues a
/// one-shot background job with no domain uniqueness check to catch a
/// duplicate, unlike an ordinary `create_*` route (a duplicate-slug 409 or a
/// unique-constraint violation once the retry re-executes). Releasing the
/// row on a 5xx here would let an immediate retry silently enqueue a second
/// job, so `component_routes!`'s `one_shot` modifier wires these two to a
/// short-lived stored replay instead
/// (`middleware::idempotency::idempotency_middleware_store_briefly`). Every
/// other `idempotent: true` route uses `Release`
/// (`idempotency_middleware_release`): `PgIdempotencyRepo::release` deletes
/// the row on a 5xx so the retry re-executes and the handler's own domain
/// check catches a genuine duplicate.
///
/// `tests/idempotency_declare_and_verify_audit.rs` proves this set equals,
/// in both directions (INV-SET), [`acta_one_shot_route_paths`] — same "one
/// macro expansion, one fact" property already proven for `idempotent`
/// itself. See `docs/reg5-idempotent-judgment.md`'s "5xx policy" section for
/// the reasoning behind exactly these two.
pub const ONE_SHOT_IDEMPOTENT_ROUTES: &[(HttpMethod, &str, &str)] = &[
    (
        HttpMethod::Post,
        "/admin/trash/purge",
        "purge_trash enqueues an async, tracked purge job with no domain \
         uniqueness check; a lost row would let a 5xx retry enqueue a \
         second purge job.",
    ),
    (
        HttpMethod::Post,
        "/workspaces/{ws}/semantic-search/reindex",
        "semantic_reindex_start enqueues an async reindex job with no domain \
         uniqueness check; same reasoning as purge_trash.",
    ),
];

/// D4's route-set exclusion list (`v2-e3-s2` PR5, spec "Explicit, justified
/// route exclusion list" requirement, acceptance gate 3): routes the live
/// router serves that cannot be declared as a `RouteDeclaration` today, each
/// with its own justification. This is the ONLY list of its kind in the
/// codebase — distinct from D5's per-component `DECLARE_AND_VERIFY_EXEMPT`
/// constants (`routes::acta`), which exempt a route from the
/// declared-vs-enforced capability comparison while the route itself stays
/// in the router↔registry SET audit.
///
/// Exhaustiveness is proven in both directions, never assumed:
/// - `route_set_exclusions_are_not_declared_anywhere` (this module's test
///   suite) proves no entry here is secretly a real, already-declared route
///   (a "dead exclusion" that would silently absorb drift, D4's own stated
///   risk).
/// - `tests/api_route_exclusion_list.rs` spawns the real `atlas_server::app()`
///   and proves each entry is actually served, with a foreign-method probe
///   expecting 405 (neither route sits behind `require_authn`, so this
///   works exactly like the T4.9 mount probe).
///
/// What this list does NOT prove, and cannot: that no OTHER route exists
/// which is neither declared by any component nor named here. axum 0.8
/// exposes no router introspection, so there is no way to enumerate "every
/// path this live router actually serves" from outside it — only to ask
/// "is this specific candidate path served?" The inside of that gap is
/// covered structurally instead: SH10 (this module's own regression test)
/// proves a route added to a component's router without a matching
/// `declared_routes()` entry fails `cargo test`, so any route bypassing a
/// component's `component_routes!` macro is caught at the SOURCE it would
/// have to be added through, not by an external enumeration this list could
/// never provide.
///
/// **Currently empty** (`v2-e3-s4`, D3): `RoutePath` now accepts one
/// interior dot in a path's final segment, so `/openapi.json` and `/scalar`
/// — the only two entries this list ever held — are ordinary
/// `RouteDeclaration`s under `platform` (`reg5.rs`) as of this slice. The
/// list and its two completeness tests
/// (`route_set_exclusions_are_not_declared_anywhere` below,
/// `tests/api_route_exclusion_list.rs`) are kept, not deleted, as a live,
/// checked escape hatch for the next route `RoutePath` genuinely cannot
/// express — see `route_set_exclusions_is_empty` for the explicit,
/// checkable claim over this empty state.
pub const ROUTE_SET_EXCLUSIONS: &[(atlas_core::registry::HttpMethod, &str)] = &[];

fn component_route_paths(routes: &[AuditedRoute]) -> Vec<(HttpMethod, &'static str)> {
    routes
        .iter()
        .map(|route| (route.method, route.path))
        .collect()
}

/// Test-only support shared by every per-component audit test in this crate
/// (this module's own scratch fixtures, plus `routes::platform`'s real
/// audit in PR2 and its PR3/PR4 successors).
#[cfg(test)]
pub(crate) mod test_support {
    #![allow(clippy::expect_used)]

    use std::collections::HashSet;

    use atlas_core::registry::HttpMethod;
    use axum::body::Body;
    use axum::http::{Method, Request, StatusCode};
    use tower::ServiceExt;

    fn axum_method_of(method: HttpMethod) -> Method {
        match method {
            HttpMethod::Get => Method::GET,
            HttpMethod::Post => Method::POST,
            HttpMethod::Put => Method::PUT,
            HttpMethod::Patch => Method::PATCH,
            HttpMethod::Delete => Method::DELETE,
            HttpMethod::Head => Method::HEAD,
            HttpMethod::Options => Method::OPTIONS,
        }
    }

    /// Sends one request per candidate through the live router and returns
    /// the subset it actually serves. This is the only way to learn what an
    /// axum 0.8 `Router` really has mounted — axum exposes no introspection
    /// — and is legitimate here specifically because the caller already
    /// knows every candidate to probe (it built the declared set itself);
    /// it is not a stand-in for the real per-component audit, which never
    /// probes a live router at all and instead compares `declared_routes()`
    /// against the registry (D2).
    ///
    /// Both `404 Not Found` (no path node at all) and `405 Method Not
    /// Allowed` (the path exists, but not for this method — the shape a
    /// multi-method path returns for an undeclared method) mean "not
    /// served"; only classifying `404` would wrongly count an undeclared
    /// method on an *already-mounted* multi-method path as served.
    pub(crate) async fn probe_served_routes(
        router: axum::Router,
        candidates: &[(HttpMethod, &'static str)],
    ) -> HashSet<(HttpMethod, &'static str)> {
        let mut served = HashSet::new();

        for &(method, path) in candidates {
            let request = Request::builder()
                .method(axum_method_of(method))
                .uri(path)
                .body(Body::empty())
                .expect("valid scratch request");

            let response = router
                .clone()
                .oneshot(request)
                .await
                .expect("scratch router must respond");

            if !matches!(
                response.status(),
                StatusCode::NOT_FOUND | StatusCode::METHOD_NOT_ALLOWED
            ) {
                served.insert((method, path));
            }
        }

        served
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
    #![allow(clippy::unused_async, reason = "scratch handler shapes only")]
    #![allow(
        dead_code,
        reason = "scope_extraction::router() only needs to type-check the macro's \
                  real-component shape (AppState, Authorized<...>); these tests exercise \
                  declared_routes() only, never mount or call router()"
    )]
    #![allow(
        unreachable_pub,
        reason = "component_routes! always emits `pub fn router` to match the real \
                  per-component contract (D1); it is only unreachable here because these \
                  scratch modules are test-private, not because the macro emits it wrong"
    )]

    use super::test_support::probe_served_routes;
    use super::*;
    use axum::body::Body;
    use axum::http::{Method, Request, StatusCode};
    use tower::ServiceExt;

    #[test]
    fn canonical_namespace_is_the_v1_namespace() {
        assert_eq!(V1_NAMESPACE, CANONICAL_NAMESPACE);
    }

    #[test]
    fn namespaces_for_returns_v1_then_the_components_own_v2_prefix() {
        for component in ["platform", "custos", "acta"] {
            assert_eq!(
                namespaces_for(component),
                [V1_NAMESPACE.to_string(), format!("{V2_PREFIX}/{component}")]
            );
        }
    }

    #[test]
    fn v2_namespace_reads_namespaces_fors_second_element() {
        for component in ["platform", "custos", "acta"] {
            let [_v1, v2] = namespaces_for(component);
            assert_eq!(v2_namespace(component), v2);
        }
    }

    fn declared_set(routes: &[AuditedRoute]) -> HashSet<(HttpMethod, &'static str)> {
        routes
            .iter()
            .map(|route| (route.method, route.path))
            .collect()
    }

    /// A scratch, state-free component proving the mechanism (T1.1–T1.6):
    /// `component_routes!` co-generates `router(())` and `declared_routes()`
    /// from the same two-route token list, so they agree by construction.
    /// Handlers here take no `Authorized<...>` extractor — that mechanism
    /// belongs to `scope_extraction`, below — so every entry is `exempt`.
    mod scratch_mechanism {
        use axum::http::StatusCode;

        async fn ping() -> StatusCode {
            StatusCode::OK
        }

        async fn version() -> StatusCode {
            StatusCode::OK
        }

        crate::component_routes! {
            state: ();
            "/scratch/ping" => [ get(ping, exempt) ];
            "/scratch/version" => [ get(version, exempt) ];
        }
    }

    /// SH10, undeclared-route direction (T1.1/T1.2 GREEN case).
    #[tokio::test]
    async fn matched_router_and_declared_sets_pass() {
        let declared = declared_set(&scratch_mechanism::declared_routes());
        let live = probe_served_routes(
            scratch_mechanism::router(()),
            &[
                (HttpMethod::Get, "/scratch/ping"),
                (HttpMethod::Get, "/scratch/version"),
            ],
        )
        .await;

        let diff = diff_route_sets(&declared, &live);

        assert!(
            diff.is_empty(),
            "matched sets must not report a mismatch: {diff:?}"
        );
    }

    /// SH10 (T1.3/T1.4): a route added directly to the router's `Router`
    /// value, bypassing `component_routes!` entirely, has no
    /// `declared_routes()` entry. The bidirectional audit must fail and name
    /// exactly that route — this is the audit's own regression test. If this
    /// test ever passes for the wrong reason (a bug in `probe_served_routes`
    /// or `diff_route_sets` that always reports "empty"), the assertion on
    /// the *named* offending route below (not just "diff is non-empty")
    /// catches it: a no-op audit could not possibly know which route is
    /// bypassed. This test's purpose is to prove the audit has teeth, not to
    /// prove the macro works (T1.1 already proves that).
    #[tokio::test]
    async fn undeclared_route_added_outside_the_macro_fails_the_audit() {
        async fn bypass() -> axum::http::StatusCode {
            axum::http::StatusCode::OK
        }

        let router_with_bypass =
            scratch_mechanism::router(()).route("/scratch/bypass", axum::routing::get(bypass));

        let declared = declared_set(&scratch_mechanism::declared_routes());
        let live = probe_served_routes(
            router_with_bypass,
            &[
                (HttpMethod::Get, "/scratch/ping"),
                (HttpMethod::Get, "/scratch/version"),
                (HttpMethod::Get, "/scratch/bypass"),
            ],
        )
        .await;

        let diff = diff_route_sets(&declared, &live);

        assert!(
            !diff.is_empty(),
            "an undeclared-but-served route must be caught"
        );
        assert_eq!(
            diff.right_only,
            vec![(HttpMethod::Get, "/scratch/bypass")],
            "the audit must name exactly the offending route, not just fail"
        );
        assert!(diff.left_only.is_empty());
    }

    /// Reverse direction (T1.5): a route present in `declared_routes()` that
    /// is never actually mounted. Because `component_routes!` always
    /// generates both outputs together, this direction can only be produced
    /// by taking a real `declared_routes()` result and appending an entry by
    /// hand — exactly the shape of a developer editing the declared list
    /// without touching the router, which is what this direction protects
    /// against once real components use the macro's declared side alongside
    /// a hand-maintained one (or, in PR2+, alongside the registry).
    #[tokio::test]
    async fn declared_route_never_mounted_fails_the_audit() {
        let mut declared_routes = scratch_mechanism::declared_routes();
        declared_routes.push(AuditedRoute {
            method: HttpMethod::Get,
            path: "/scratch/never-mounted",
            scope: DeclaredScope::Unauthenticated,
            idempotent: false,
            one_shot: false,
        });

        let declared = declared_set(&declared_routes);
        let live = probe_served_routes(
            scratch_mechanism::router(()),
            &[
                (HttpMethod::Get, "/scratch/ping"),
                (HttpMethod::Get, "/scratch/version"),
                (HttpMethod::Get, "/scratch/never-mounted"),
            ],
        )
        .await;

        let diff = diff_route_sets(&declared, &live);

        assert!(!diff.is_empty());
        assert_eq!(
            diff.left_only,
            vec![(HttpMethod::Get, "/scratch/never-mounted")]
        );
        assert!(diff.right_only.is_empty());
    }

    /// T1.6: one call to `diff_route_sets` catches both directions at once
    /// — router-only AND declared-only — proving PR2–PR4 need exactly one
    /// audit helper per component, not two separate checks.
    #[tokio::test]
    async fn one_diff_call_catches_both_directions_simultaneously() {
        async fn bypass() -> axum::http::StatusCode {
            axum::http::StatusCode::OK
        }

        let mut declared_routes = scratch_mechanism::declared_routes();
        declared_routes.push(AuditedRoute {
            method: HttpMethod::Get,
            path: "/scratch/never-mounted",
            scope: DeclaredScope::Unauthenticated,
            idempotent: false,
            one_shot: false,
        });

        let router_with_bypass =
            scratch_mechanism::router(()).route("/scratch/bypass", axum::routing::get(bypass));

        let declared = declared_set(&declared_routes);
        let live = probe_served_routes(
            router_with_bypass,
            &[
                (HttpMethod::Get, "/scratch/ping"),
                (HttpMethod::Get, "/scratch/version"),
                (HttpMethod::Get, "/scratch/bypass"),
                (HttpMethod::Get, "/scratch/never-mounted"),
            ],
        )
        .await;

        let diff = diff_route_sets(&declared, &live);

        assert_eq!(
            diff.left_only,
            vec![(HttpMethod::Get, "/scratch/never-mounted")]
        );
        assert_eq!(diff.right_only, vec![(HttpMethod::Get, "/scratch/bypass")]);
    }

    /// A scratch component proving several methods on the same path fold
    /// into one `.route()` call while `declared_routes()` still lists every
    /// `(method, path)` pair individually: one path with two methods, one
    /// with three, five distinct handlers.
    mod scratch_multi_method {
        use axum::http::StatusCode;

        async fn multi_two_get() -> StatusCode {
            StatusCode::OK
        }

        async fn multi_two_post() -> StatusCode {
            StatusCode::OK
        }

        async fn multi_three_get() -> StatusCode {
            StatusCode::OK
        }

        async fn multi_three_post() -> StatusCode {
            StatusCode::OK
        }

        async fn multi_three_delete() -> StatusCode {
            StatusCode::OK
        }

        crate::component_routes! {
            state: ();
            "/scratch/multi-two" => [
                get(multi_two_get, exempt),
                post(multi_two_post, exempt)
            ];
            "/scratch/multi-three" => [
                get(multi_three_get, exempt),
                post(multi_three_post, exempt),
                delete(multi_three_delete, exempt)
            ];
        }
    }

    const MULTI_METHOD_CANDIDATES: [(HttpMethod, &str); 5] = [
        (HttpMethod::Get, "/scratch/multi-two"),
        (HttpMethod::Post, "/scratch/multi-two"),
        (HttpMethod::Get, "/scratch/multi-three"),
        (HttpMethod::Post, "/scratch/multi-three"),
        (HttpMethod::Delete, "/scratch/multi-three"),
    ];

    /// The multi-method requirement's two halves: `declared_routes()` lists
    /// one `AuditedRoute` per `(method, path)` pair (5, not 2 — one per
    /// path), and the router mounts each path exactly once, proven by a
    /// direct check that an undeclared method on a multi-method path 405s
    /// (the path node exists and knows about it) rather than 404s (which
    /// would mean two separate, accidentally-duplicated path registrations).
    #[tokio::test]
    async fn multi_method_path_mounts_once_but_audits_every_pair() {
        let declared_routes = scratch_multi_method::declared_routes();
        assert_eq!(
            declared_routes.len(),
            5,
            "one AuditedRoute per (method, path) pair, not one per path"
        );

        let declared = declared_set(&declared_routes);
        let expected: HashSet<(HttpMethod, &'static str)> =
            MULTI_METHOD_CANDIDATES.into_iter().collect();
        assert_eq!(declared, expected);

        let live =
            probe_served_routes(scratch_multi_method::router(()), &MULTI_METHOD_CANDIDATES).await;
        let diff = diff_route_sets(&declared, &live);
        assert!(
            diff.is_empty(),
            "every declared pair must be served: {diff:?}"
        );

        let response = scratch_multi_method::router(())
            .oneshot(
                Request::builder()
                    .method(Method::DELETE)
                    .uri("/scratch/multi-two")
                    .body(Body::empty())
                    .expect("valid scratch request"),
            )
            .await
            .expect("scratch router must respond");
        assert_eq!(
            response.status(),
            StatusCode::METHOD_NOT_ALLOWED,
            "an undeclared method on a mounted multi-method path is 405, not 404 — \
             proof the path was mounted once, not duplicated"
        );
    }

    /// SH10, multi-method variant: an undeclared method squeezed onto an
    /// already-multi-method path (bypassing the macro, exactly like the
    /// single-method SH10 test above) must still be named by the audit.
    #[tokio::test]
    async fn multi_method_path_with_one_undeclared_method_fails_the_audit() {
        async fn bypass() -> axum::http::StatusCode {
            axum::http::StatusCode::OK
        }

        let router_with_bypass = scratch_multi_method::router(())
            .route("/scratch/multi-two", axum::routing::delete(bypass));

        let declared = declared_set(&scratch_multi_method::declared_routes());
        let mut candidates = MULTI_METHOD_CANDIDATES.to_vec();
        candidates.push((HttpMethod::Delete, "/scratch/multi-two"));
        let live = probe_served_routes(router_with_bypass, &candidates).await;

        let diff = diff_route_sets(&declared, &live);

        assert_eq!(
            diff.right_only,
            vec![(HttpMethod::Delete, "/scratch/multi-two")]
        );
        assert!(diff.left_only.is_empty());
    }

    /// A scratch component proving `ExtractScope` extraction is wired all
    /// the way through `component_routes!` (T1.9–T1.14), across three
    /// arities (0, 2, 4 extra parameters after `Authorized<...>`), one
    /// non-default `S`, and the capability-extraction exemption scaffold.
    /// `router(state: AppState)` only has to type-check here — it is never
    /// called, so no database or `AppState` value is ever constructed.
    mod scope_extraction {
        use crate::authz::{Authorized, NoScope, TasksRead, ViewerMin, WorkspaceRes};
        use crate::state::AppState;
        use axum::extract::{Path, Query, State};
        use axum::http::StatusCode;
        use std::collections::HashMap;

        async fn arity_zero(_auth: Authorized<WorkspaceRes, ViewerMin, NoScope>) -> StatusCode {
            StatusCode::OK
        }

        async fn arity_two(
            _auth: Authorized<WorkspaceRes, ViewerMin, NoScope>,
            State(_state): State<AppState>,
            Query(_q): Query<HashMap<String, String>>,
        ) -> StatusCode {
            StatusCode::OK
        }

        async fn arity_four(
            _auth: Authorized<WorkspaceRes, ViewerMin, TasksRead>,
            State(_state): State<AppState>,
            Path(_id): Path<String>,
            Query(_q): Query<HashMap<String, String>>,
        ) -> StatusCode {
            StatusCode::OK
        }

        /// No `Authorized<...>` extractor at all — mirrors `health`/`ready`
        /// /`version`, the capability-extraction exemption list (D5).
        async fn scratch_health() -> StatusCode {
            StatusCode::OK
        }

        crate::component_routes! {
            state: AppState;
            "/scratch/arity-zero" => [ get(arity_zero) ];
            "/scratch/arity-two" => [ get(arity_two) ];
            "/scratch/arity-four" => [ get(arity_four) ];
            "/scratch/health" => [ get(scratch_health, exempt) ];
        }
    }

    fn capability(
        family: atlas_custos::capability::CapabilityFamily,
        action: atlas_custos::capability::CapabilityAction,
    ) -> Capability {
        Capability { family, action }
    }

    /// T1.9/T1.10/T1.13: `component_routes!` calls `declared_scope()` for
    /// every non-exempt entry, resolving the right capability for each of
    /// three arities and the one pinned non-default `S`; the exempt entry
    /// records `Unauthenticated` without attempting extraction.
    #[test]
    fn component_routes_extracts_the_right_scope_for_every_arity() {
        use atlas_custos::capability::{CapabilityAction, CapabilityFamily};

        let routes = scope_extraction::declared_routes();

        let scope_of = |path: &str| {
            routes
                .iter()
                .find(|route| route.path == path)
                .unwrap_or_else(|| panic!("no declared route for {path}"))
                .scope
        };

        assert_eq!(
            scope_of("/scratch/arity-zero"),
            DeclaredScope::Extracted(None)
        );
        assert_eq!(
            scope_of("/scratch/arity-two"),
            DeclaredScope::Extracted(None)
        );
        assert_eq!(
            scope_of("/scratch/arity-four"),
            DeclaredScope::Extracted(Some(capability(
                CapabilityFamily::Tasks,
                CapabilityAction::Read
            )))
        );
        assert_eq!(scope_of("/scratch/health"), DeclaredScope::Unauthenticated);
    }

    /// T1.11/T1.12: a route's declared action (registry side, stood in here
    /// by a hand-built map — PR2+ reads the real `RouteDeclaration.action`)
    /// disagreeing with the handler's enforced capability fails, naming the
    /// offending route and both sides of the mismatch.
    #[test]
    fn declare_and_verify_names_the_offending_route_and_both_sides() {
        use atlas_custos::capability::{CapabilityAction, CapabilityFamily};

        let routes = scope_extraction::declared_routes();
        let declared_actions = HashMap::from([
            ((HttpMethod::Get, "/scratch/arity-zero"), None),
            ((HttpMethod::Get, "/scratch/arity-two"), None),
            (
                (HttpMethod::Get, "/scratch/arity-four"),
                Some(capability(CapabilityFamily::Boards, CapabilityAction::Read)),
            ),
            ((HttpMethod::Get, "/scratch/health"), None),
        ]);

        let mismatches = diff_declared_and_enforced(&routes, &declared_actions);

        assert_eq!(
            mismatches,
            vec![ScopeMismatch {
                method: HttpMethod::Get,
                path: "/scratch/arity-four",
                declared: Some(capability(CapabilityFamily::Boards, CapabilityAction::Read)),
                enforced: Some(capability(CapabilityFamily::Tasks, CapabilityAction::Read)),
            }]
        );
    }

    /// T1.14: marking a handler `exempt` skips `declared_scope()` entirely —
    /// `scratch_health` has no `Authorized<...>` parameter and still
    /// type-checks inside `component_routes!` only because it is exempt.
    /// The audit still requires the registry side to declare `action: None`
    /// for it: a registry entry that wrongly claims a capability for an
    /// exempt route is a mismatch, exactly like any other drift.
    #[test]
    fn exemption_scaffold_requires_the_registry_side_to_declare_no_action() {
        let health_route: Vec<AuditedRoute> = scope_extraction::declared_routes()
            .into_iter()
            .filter(|route| route.path == "/scratch/health")
            .collect();
        assert_eq!(health_route.len(), 1, "exactly one scratch health route");
        assert_eq!(
            health_route.first().unwrap().scope,
            DeclaredScope::Unauthenticated
        );

        let agreeing = HashMap::from([((HttpMethod::Get, "/scratch/health"), None)]);
        assert!(diff_declared_and_enforced(&health_route, &agreeing).is_empty());

        let drifted = HashMap::from([(
            (HttpMethod::Get, "/scratch/health"),
            Some(capability(
                atlas_custos::capability::CapabilityFamily::Tasks,
                atlas_custos::capability::CapabilityAction::Read,
            )),
        )]);
        let mismatches = diff_declared_and_enforced(&health_route, &drifted);

        assert_eq!(mismatches.len(), 1);
        let mismatch = mismatches.first().unwrap();
        assert_eq!(mismatch.path, "/scratch/health");
        assert_eq!(mismatch.enforced, None);
    }

    /// T5.8, direction (a): no [`ROUTE_SET_EXCLUSIONS`] entry is secretly a
    /// real, already-declared route. If one were, it would be a "dead
    /// exclusion" (D4's own named risk) that silently absorbs a route
    /// drifting out of its owning component's declarations instead of
    /// failing the bidirectional audit — this test would then need to be the
    /// one to catch it, since the per-component set-equality audits never
    /// see `ROUTE_SET_EXCLUSIONS` at all (neither side of their comparison —
    /// `declared_routes()` nor the registry's `api.routes` — can express
    /// `/openapi.json` or `/scalar` in the first place).
    #[test]
    fn route_set_exclusions_are_not_declared_anywhere() {
        let declared: HashSet<(HttpMethod, &'static str)> =
            crate::routes::platform::declared_routes()
                .into_iter()
                .chain(crate::routes::custos::declared_routes())
                .chain(crate::routes::acta::declared_routes())
                .map(|route| (route.method, route.path))
                .collect();

        for &(method, path) in ROUTE_SET_EXCLUSIONS {
            assert!(
                !declared.contains(&(method, path)),
                "{method:?} {path} is in ROUTE_SET_EXCLUSIONS but is ALSO declared by a \
                 component — remove it from the exclusion list, it no longer needs one"
            );
        }
    }

    /// T1.8/T1.9 (`v2-e3-s4`, D3): a real, checkable claim over the list's
    /// current state, not an implicit pass-by-vacuity of the loop above (a
    /// loop over an empty slice passes trivially regardless of whether the
    /// list was ever meant to be empty). If a future PR reintroduces an
    /// exclusion without updating this assertion, this test fails and names
    /// why.
    #[test]
    fn route_set_exclusions_is_empty() {
        assert!(
            ROUTE_SET_EXCLUSIONS.is_empty(),
            "ROUTE_SET_EXCLUSIONS must be empty as of v2-e3-s4 D3 — every route it used to \
             hold is now an ordinary RouteDeclaration; update this assertion deliberately if a \
             future route genuinely needs the escape hatch"
        );
    }

    /// T2.30 (`v2-e3-s4`, D7, R7's mitigation): the pre-D7 hand literal this
    /// test used to compare against, run one more time BEFORE its deletion
    /// (below), as the independent check that
    /// `{platform,custos,acta}_route_paths()`'s union is currently correct.
    /// Recorded in the PR description; this is not a new assertion, only a
    /// paper trail that the union was verified once before `is_public`
    /// started trusting it as ground truth.
    #[test]
    fn pre_d7_independent_literal_matches_the_route_paths_union() {
        const EXPECTED_PUBLIC_ROUTES: &[(HttpMethod, &str)] = &[
            (HttpMethod::Get, "/health"),
            (HttpMethod::Get, "/ready"),
            (HttpMethod::Get, "/version"),
            (HttpMethod::Post, "/auth/login"),
            (HttpMethod::Get, "/activate/{token}"),
            (HttpMethod::Post, "/activate/{token}"),
            (
                HttpMethod::Post,
                "/workspaces/{ws}/integrations/{integration}/events",
            ),
            (HttpMethod::Get, "/openapi.json"),
            (HttpMethod::Get, "/scalar"),
        ];

        let expected: HashSet<(HttpMethod, &'static str)> =
            EXPECTED_PUBLIC_ROUTES.iter().copied().collect();
        let actual: HashSet<(HttpMethod, &'static str)> = platform_route_paths()
            .into_iter()
            .chain(custos_route_paths())
            .chain(acta_route_paths())
            .collect();

        let diff = diff_route_sets(&expected, &actual);
        assert!(
            diff.is_empty(),
            "the pre-D7 independent literal no longer matches the route_paths() union — a \
             latent discrepancy here would have been baked into is_public as ground truth: \
             {diff:?}"
        );
    }

    /// T2.31 (`v2-e3-s4`, D7): replaces the hand literal above with
    /// `Registry::all_routes().filter(|r| r.is_public)` — both sides stay
    /// independent of each other post-D7: this side reads `is_public` off
    /// `reg5.rs`, the other reads the router-accessor union built from the
    /// live `component_routes!` expansion.
    #[test]
    fn public_route_set_matches_route_paths_union() {
        use atlas_core::registry::build;

        let registry = build(crate::reg5::reg5_component_entries(
            crate::reg5::StorageBackend::Filesystem,
        ))
        .expect("REG-5 entries must satisfy every registry::build() validator");

        let declared_public: HashSet<(HttpMethod, String)> = registry
            .entries()
            .iter()
            .flat_map(|entry| entry.api.routes.iter())
            .filter(|route| route.is_public)
            .map(|route| (route.method, route.path.as_str().to_string()))
            .collect();

        let mounted_public: HashSet<(HttpMethod, String)> = platform_route_paths()
            .into_iter()
            .chain(custos_route_paths())
            .chain(acta_route_paths())
            .map(|(method, path)| (method, path.to_string()))
            .collect();

        let diff = diff_route_sets(&declared_public, &mounted_public);
        assert!(
            diff.left_only.is_empty(),
            "declared is_public: true but not actually mounted with no require_authn layer: {:?}",
            diff.left_only
        );
        assert!(
            diff.right_only.is_empty(),
            "mounted with no require_authn layer but not declared is_public: true: {:?}",
            diff.right_only
        );
    }
}
